#!/usr/bin/env bash

# Get paths of staged files, excluding deleted files
files="$(git diff --cached --name-only --diff-filter=d HEAD)"
shell_files="$(echo "$files" | file --files-from - | grep -e 'shell' -e ' sh script' | cut -d : -f 1)"

if [ -z "$shell_files" ]; then
	echo 'nothing to format'
	exit 0
fi

if ! command -v shfmt >/dev/null; then
	echo 'error: shfmt is not installed'
	exit 1
fi

if ! command -v shellcheck >/dev/null; then
	echo 'error: shellcheck is not installed'
	exit 1
fi

pushd "$(git rev-parse --show-toplevel)" > /dev/null || exit

bootstrap_path='bin/,bootstrap'
if [[ $shell_files == *"$bootstrap_path"* ]] && ! shfmt --ln posix "$bootstrap_path" >/dev/null; then
	echo "error: $bootstrap_path must be POSIX-compatible"
	exit 1
fi

for file in $shell_files; do
	# -s: simplify code
	# -i 0: indent with one tab
	shfmt_args=(-s -i 0 "$file")

	if ! shfmt "${shfmt_args[@]}" > /dev/null; then
		echo "formatting $file"
		# -w: write in place
		shfmt -w "${shfmt_args[@]}"
		exit 1
	fi

	shellcheck --external-sources "$file"
done
