#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component config "$@"
}

log_start 'setting up bat'
bat_config_dir="$(bat --config-dir)"
theme_dir="$bat_config_dir"/themes
mkdir -p "$theme_dir"

# https://github.com/catppuccin/bat
if ! _curl https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme --output "$theme_dir/Catppuccin Latte.tmTheme"; then
	fatal 'failed to download theme'
fi
if ! _curl https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme --output "$theme_dir/Catppuccin Macchiato.tmTheme"; then
	fatal 'failed to download theme'
fi

# Update the binary cache
bat cache --build
log_end
