#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

# Refresh existing sudo session or start a new one
# shellcheck disable=SC2119
request-sudo

message "magenta" "  %s" "updating Brew package lists..."
brew update >/dev/null

message "magenta" "  %s" "installing Brew formulas..."
if ! brew bundle install --no-lock; then
	warn "installing Brew formulas may have failed"
fi

if "$_dir"/../bin/is-macos && brew services list | grep --quiet --extended-regexp 'emacs .+ stopped'; then
	message "magenta" "  %s" "enabling Emacs service..."
	if brew services start emacs; then
		message "magenta" "  %s" "enabled Emacs service."
	else
		warn "failed to enable Emacs service."
	fi
fi

message "magenta" "brew done."
