#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component brew "$@"
}

log_start 'setting up Homebrew'

# Refresh existing sudo session or start a new one
# shellcheck disable=SC2119
request_sudo

log_start 'updating package lists'
brew update >/dev/null
log_end

log_start 'installing formulas'
if ! brew bundle install --no-lock; then
	warn 'installing formulas may have failed'
fi
log_end

log_end
