#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component codex "$@"
}

codex_home="${CODEX_HOME:-$HOME/.codex}"

log_start 'setting up Codex'

if ! [ -s "$codex_home"/config.toml ]; then
	log_start 'copying Codex configuration'
	mkdir -p "$codex_home"
	export XDG_CACHE_HOME
	XDG_CACHE_HOME="$(xdg_cache)"
	export XDG_CONFIG_HOME
	XDG_CONFIG_HOME="$(xdg_config)"
	envsubst <"$script_dir"/../config/codex/config.toml >"$codex_home"/config.toml
	log_end
fi
_ln "$script_dir"/../config/codex/codex-agents.md "$codex_home"/AGENTS.md
mkdir -p "$codex_home"/rules
_ln "$script_dir"/../config/codex/rules/custom.rules "$codex_home"/rules/custom.rules

log_start 'linking skills'
mkdir -p "$HOME"/.agents/skills
_ln "$script_dir"/../config/skills/* "$HOME"/.agents/skills
log_end

log_end
