#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component config "$@"
}

log_start 'setting up configuration'

config_dir="$(xdg_config)"
codex_home="${CODEX_HOME-$HOME/.codex}"

if is_devcontainer; then
	log_start 'ensuring config directories exist'
	mkdir -vp "$config_dir" "$codex_home"
	log_end
	log_start 'ensuring correct ownership of config directories'
	request_sudo chown --recursive "${USER:-$(id --name --user)}":"${GROUP:-$(id --name --group)}" "$config_dir" "$codex_home"
	log_end
fi

log "symlinking dotfiles to \"$HOME\""
_ln "$script_dir"/../.bashrc "$HOME"
_ln "$script_dir"/../.profile "$HOME"

bin_dir="$HOME"/.local/bin
log "creating \"$bin_dir\""
mkdir -p "$bin_dir"

log "symlinking executables to \"$bin_dir\""
_ln "$script_dir"/../bin/* "$bin_dir"

log "symlinking configurations to \"$config_dir\""
mkdir -p "$config_dir"/ripgrep
_ln "$script_dir"/../config/ripgrep "$config_dir"/ripgrep/config

mkdir -p "$config_dir"/bat
_ln "$script_dir"/../config/bat "$config_dir"/bat/config

mkdir -p "$config_dir"/glow
_ln "$script_dir"/../config/glow.yml "$config_dir"/glow/glow.yml

if ! [ -d "$config_dir"/docker ]; then
	log 'creating Docker configuration directory'
	mkdir -p "$config_dir"/docker
fi

cp "$script_dir"/../config/kdiff3rc "$config_dir"/kdiff3rc

mkdir -p "$config_dir"/kitty
_ln "$script_dir"/../config/kitty/* "$config_dir"/kitty
if command -v kitten >/dev/null; then
	kitten themes --dump-theme Catppuccin-Macchiato >"$config_dir"/kitty/dark-theme.auto.conf
	kitten themes --dump-theme Catppuccin-Latte >"$config_dir"/kitty/light-theme.auto.conf
	kitten themes --dump-theme Catppuccin-Latte >"$config_dir"/kitty/no-preference-theme.auto.conf
fi

log "creating tig directory"
# Prevent tig from writing ~/.tig_history
mkdir -p "$(xdg_data)"/tig

if ! [ -s "$codex_home"/config.toml ]; then
	log 'copying Codex configuration'
	mkdir -p "$codex_home"
	export XDG_CACHE_HOME
	XDG_CACHE_HOME="$(xdg_cache)"
	export XDG_CONFIG_HOME
	XDG_CONFIG_HOME="$(xdg_config)"
	envsubst <"$script_dir"/../config/codex.toml >"$codex_home"/config.toml
fi

log_end
