#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component 'dns' "$@"
}

if ! nextdns config list | grep --quiet 'profile'; then
	log_start 'setting up NextDNS CLI'
	read -r -p "$(make_prompt 'NextDNS profile:') " profile
	if [ -n "$profile" ]; then
		request_sudo nextdns install \
			-auto-activate \
			-cache-size 10MB \
			-detect-captive-portals \
			-max-ttl 5s \
			-profile "$profile" \
			-report-client-info
	else
		warn 'must provide a NextDNS profile ID, skipping setup'
	fi
	log_end
fi
