#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component emacs "$@"
}

log_start 'setting up Emacs'

log_start 'setting up Emacs configuration'
emacs_config_dir="$(xdg_config)"/emacs
emacs_config_path="$emacs_config_dir"/init.el
if ! [ -f "$emacs_config_path" ]; then
	log_start 'installing Emacs configuration'
	mkdir -p "$emacs_config_dir"
	_ln "$script_dir"/../config/emacs.el "$emacs_config_path"
	log_end
fi

log_start 'installing Emacs early init file'
# https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html
cat >"$emacs_config_dir"/early-init.el <<-EOF
	;; Do not run "site files" from e.g. /etc/emacs/site-start.d/
	(setq site-run-file nil)
EOF
log_end

emacs_local_config_path="$emacs_config_dir"/lisp/init-local.el
if ! [ -f "$emacs_local_config_path" ]; then
	log_start 'installing template for local Emacs configuration'
	mkdir -p "$emacs_config_dir"/lisp
	cat >"$emacs_local_config_path" <<-EOF
		;;; init-local.el --- Local configuration overrides for Emacs.
		;;; Commentary:

		;;; Local, machine-specific configuration for Emacs.

		;;; Code:

		; (setq initial-buffer-choice "~/<path to file to open at launch>")
		; (setq org-directory "~/<path to org directory>")
		; (setq org-agenda-files '("~/<path to file to use for org agenda>"))

		(provide 'init-local)

		;; Local Variables:
		;; byte-compile-warnings: (not free-vars unresolved)
		;; End:
		;;; init-local.el ends here
	EOF
	log_end
fi

if is_macos; then
	log_start 'linking Emacs configuration to home directory for macOS Emacs'
	mkdir -p "$HOME"/.emacs.d/lisp
	_ln "$emacs_config_path" "$HOME"/.emacs.d
	_ln "$emacs_local_config_path" "$HOME"/.emacs.d/lisp
	log_end
fi
log_end

if [ -f "$HOME"/.emacs.d ]; then
	log 'removing config directory at default location to avoid conflicts'
	rm -f "$HOME"/.emacs.d
fi

if (is_ubuntu || is_debian) && ! is_devcontainer; then
	if ! systemctl --user is-enabled --quiet emacs.service; then
		log_start 'setting up Emacs daemon'
		systemctl --user enable --now emacs.service
		log_end
	fi
else
	# Get Emacs' initial setup out of the way upfront
	emacs --batch --eval '(message "Emacs warmed")' || true
fi

log_end
