#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

if "$_dir"/../bin/is-macos && brew services list | grep --quiet --extended-regexp 'emacs .+ stopped'; then
	log 'enabling Emacs service...'
	if brew services start emacs; then
		log 'enabled Emacs service.'
	else
		warn 'failed to enable Emacs service.'
	fi
fi

if command -v lsb_release >/dev/null && [ "$(lsb_release --id --short)" = 'Ubuntu' ]; then
	user_emacs_unit_path="$(xdg_config)"/systemd/user/emacs-snapshot.service
	if ! [ -f "$user_emacs_unit_path" ]; then
		log 'linking Emacs snapshot service into place...'
		if ! package_emacs_unit_path="$(find /usr/lib -name emacs-snapshot.service)"; then
			fatal 'failed to find path to Emacs Systemd unit'
		fi
		systemctl --user link "$package_emacs_unit_path"
		# Create an alias from "emacs-snapshot" to "emacs" for more convenient usage
		ln -sf "$user_emacs_unit_path" "$(xdg_config)"/systemd/user/emacs.service
		systemctl --user daemon-reload
		log 'done linking Emacs snapshot service into place.'
	fi

	if ! systemctl --user is-enabled --quiet emacs-snapshot.service; then
		log 'setting up Emacs daemon...'
		systemctl --user enable --now emacs-snapshot.service
		log 'done setting up Emacs daemon.'
	fi

	emacs_client_desktop_path="$HOME"/.local/share/applications/emacs-client.desktop
	if ! [ -f "$emacs_client_desktop_path" ]; then
		log 'installing Emacs client desktop file...'
		mkdir -p "$(dirname "$emacs_client_desktop_path")"
		echo '[Desktop Entry]
Version=1.0
Name=Emacs (Client)
GenericName=Text Editor
Comment=GNU Emacs is an extensible, customizable text editor - and more
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
TryExec=/usr/bin/emacsclient
Exec=/usr/bin/emacsclient --create-frame --alternate-editor emacs %F
Icon=emacs
Type=Application
Terminal=false
Categories=Utility;Development;TextEditor;
StartupWMClass=Emacs
Keywords=Text;Editor;
' >"$emacs_client_desktop_path"
		log 'done installing Emacs client desktop file.'
	fi
fi

log 'setting up Emacs configuration...'
# Remove legacy configuration location
rm -f "$HOME"/.emacs

emacs_config_path="$HOME"/.emacs.d/init.el
if ! [ -f "$emacs_config_path" ]; then
	mkdir -p "$(dirname "$emacs_config_path")"
	ln -sf "$_dir"/../config/emacs.el "$emacs_config_path"
fi
log 'done setting up Emacs configuration.'
