#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component 'flatpak' "$@"
}

log_start 'installing Flatpak software'

if ! command -v flatpak >/dev/null; then
	log_start 'installing Flatpak'
	if command -v apt >/dev/null; then
		request_sudo apt-get install --yes flatpak
	else
		warn_and_bail 'cannot install Flatpak on this platform, skipping installation'
	fi
	log_end
fi

if [ -z "$(flatpak remotes)" ]; then
	log_start 'configuring Flathub remote'
	request_sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
	log_end
fi

log_start 'installing Discord'
flatpak install --assumeyes --noninteractive --or-update com.discordapp.Discord
log_end

log_start 'removing no-longer-needed packages'
flatpak uninstall --assumeyes --noninteractive com.bitwarden.desktop
log_end

log_end
