#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component gh "$@"
}

log_start 'setting up GitHub CLI (gh)'

if ! command -v gh >/dev/null; then
	warn 'could not find command "gh", skipping'
	log_end
	exit
fi

log_start 'setting configuration'
# Use SSH for Git clone and push operations
gh config set git_protocol ssh
log_end

log_start 'setting aliases'
# Create a pull request
# $1: base branch
# $2: title
# shellcheck disable=SC2016
gh alias set prc --shell 'gh pr create --assignee=@me --base="$1" --body="$(echo "**Commits**"; log-branch-commits --pr "$1")" --title="$2"'

# Create a draft pull request
# $1: base branch
# $2: title
# shellcheck disable=SC2016
gh alias set prcd --shell 'gh pr create --assignee=@me --base="$1" --body="$(echo "**Commits**"; log-branch-commits --pr "$1")" --title="$2" --draft'

# Update the body of the pull request for the current branch
# $1: base branch
# shellcheck disable=SC2016
gh alias set update-pr --shell 'gh pr edit --body="$(echo "**Commits**"; log-branch-commits --pr "$1")"'

log_end

log_start 'installing extensions'
declare -a gh_extensions=(
)

for gh_extension in "${gh_extensions[@]}"; do
	log "$gh_extension"
	gh extension install "$gh_extension" &>/dev/null || true
done
log_end

log_end
