#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component git "$@"
}

log_start 'setting up Git'

config_path="$(xdg_config)"/git
mkdir -p "$config_path"

log 'symlinking commit template'
_ln "$script_dir"/../config/git/template "$config_path"/template

log 'symlinking attributes'
_ln "$script_dir"/../config/git/attributes "$config_path"/attributes

# If gitconfig does not exist already, create one
if ! [ -e "$config_path"/config ]; then
	log "copying gitconfig to \"$config_path/config\""
	cp "$script_dir"/../config/git/config "$config_path"/config

	log_start 'configuring Git user'
	read -r -p "$(make_prompt 'Full name') " name
	read -r -p "$(make_prompt 'Email address') " email
	read -r -p "$(make_prompt 'GitHub username') " github

	# Only set values if they are non-empty
	[ -n "$name" ] && git config --global user.name "$name"
	[ -n "$email" ] && git config --global user.email "$email"
	[ -n "$github" ] && git config --global github.user "$github"
	log_end
else
	log_start 'updating Git configuration'
	# Read all values from current Git configuration
	git config --list --file "$script_dir"/../config/git/config | while read -r conf_line; do
		# Split line into name and value at equals sign
		IFS='=' read -r name value <<<"$conf_line"

		# If this configuration key is not already set, set it
		if ! git config --global "$name" &>/dev/null ||
			[ "$(git config --global "$name")" != "$value" ]; then
			# shellcheck disable=SC2016
			value="${value/'$XDG_CONFIG_HOME'/$(xdg_config)}"
			# Replace home directory with tilde for readability/portability to Dev Container
			value="${value/#$HOME/\~}"
			log "setting '$name' to '$value'"
			git config --global "$name" "$value"
		fi
	done
	log_end
fi

log_start 'configuring Delta themes'
if ! _curl https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig --output "$config_path"/delta-themes.gitconfig; then
	fatal 'failed to download Delta themes'
fi
# Replace home directory with tilde for readability/portability to Dev Container
git config --global 'include.path' "${config_path/#$HOME/\~}"/delta-themes.gitconfig
log_end

log_end
