#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component gnome "$@"
}

log_start 'setting up GNOME'

gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false
gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts false
gsettings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false
gsettings set org.gnome.shell.extensions.ding show-home false
gsettings set org.gnome.desktop.peripherals.touchpad click-method 'fingers'
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
gsettings set org.gnome.desktop.peripherals.touchpad speed -0.1
gsettings set org.gnome.shell favorite-apps '[]'
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.desktop.background picture-uri none
gsettings set org.gnome.desktop.background picture-uri-dark none
gsettings set org.gnome.desktop.background picture-options 'none'
gsettings set org.gnome.desktop.background color-shading-type 'vertical'
# Catppuccin Latte Crust
gsettings set org.gnome.desktop.background primary-color "#dce0e8"
# Catppuccin Latte Mantle
gsettings set org.gnome.desktop.background secondary-color "#e6e9ef"
gsettings set com.ubuntu.update-notifier no-show-notifications true
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.desktop.privacy remember-recent-files false
gsettings set org.gnome.desktop.interface clock-format 12h
gsettings set org.gnome.shell.keybindings screenshot "['<Shift><Super>3']"
gsettings set org.gnome.shell.keybindings screenshot-window "['<Shift><Super>5']"
gsettings set org.gnome.shell.keybindings show-screen-recording-ui "['<Shift><Super>2']"
gsettings set org.gnome.shell.keybindings show-screenshot-ui "['<Shift><Super>4']"
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Shift><Control><Alt><Super>F12'
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "bash -c 'source /home/${USER}/.profile; next-default-sink'"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Next default sink'
gsettings set org.gnome.desktop.interface show-battery-percentage true
# Disable automatic screen brightness
gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled false
# Disable "Enhanced Tiling"
gnome-extensions disable tiling-assistant@ubuntu.com
gsettings set org.gnome.settings-daemon.plugins.power idle-dim false

if ! [[ -f "$HOME"/.config/gtk-3.0/bookmarks ]]; then
	log_start 'setting Files bookmarks'
	echo "file://$HOME/files
file://$HOME/src
" >"$HOME"/.config/gtk-3.0/bookmarks
	log_end
fi

log_end
