#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component golang "$@"
}

log_start 'installing golang tools'

go_packages=(
	golang.org/x/tools/gopls # Go language server
)

for package in "${go_packages[@]}"; do
	log_file="$(mktemp)"
	if go install "$package"@latest &>"$log_file"; then
		log "installed \"$package\""
	else
		warn "package \"$package\" failed to install"
		cat "$log_file"
	fi
	rm -f "$log_file"
done

log_end
