#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component golang "$@"
}

log_start 'installing golang tools'

go_packages=(
	github.com/antonmedv/countdown # Terminal countdown timer
	github.com/genuinetools/udict  # Urban Dictionary CLI
	github.com/Rican7/define       # Dictionary/thesaurus CLI
	golang.org/x/tools/gopls       # Go language server
)

for package in "${go_packages[@]}"; do
	if go get -u "$package" &>/dev/null; then
		log "installed \"$package\""
	else
		warn "package \"$package\" failed to install"
	fi
done

log_end
