#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log "installing golang tools..."

go_packages=(
	github.com/antonmedv/countdown # Terminal countdown timer
	github.com/genuinetools/udict  # Urban Dictionary CLI
	github.com/Rican7/define       # Dictionary/thesaurus CLI
)

for package in "${go_packages[@]}"; do
	if go get -u "$package" &>/dev/null; then
		message "    %s" "installed $package"
	else
		warn "package $package failed to install"
	fi
done

log "golang done."
