#!/usr/bin/env bash

# shellcheck source=./lib/helpers
source "${BASH_SOURCE[0]%/*}/helpers"

log() {
	log_with_component grub "$@"
}

# shellcheck disable=SC2119
request_sudo

log_start 'setting up grub'

log_start 'disabling generation of recovery options'
request_sudo sed -i 's|#GRUB_DISABLE_RECOVERY="true"|GRUB_DISABLE_RECOVERY="true"|' /etc/default/grub
log_end

log_start 'enabling os-prober to detect other operating systems'
request_sudo sed -i 's|#GRUB_DISABLE_OS_PROBER=false|GRUB_DISABLE_OS_PROBER=false|' /etc/default/grub
log_end

grub_theme_dir=/boot/grub/themes/adamvig
grub_font_output_path="$grub_theme_dir"/opensans-regular.pf2
grub_theme_variable="GRUB_THEME=$grub_theme_dir/theme.txt"
log_start 'removing theme and font, disabling theme'
request_sudo rm -rf "$grub_theme_dir" "$grub_font_output_path"
if ! request_sudo sed -i "\|$grub_theme_variable|d" /etc/default/grub; then
	fatal 'failed to disable theme'
fi
log_end

grub_memtest_variable="GRUB_DISABLE_MEMTEST=true"
if ! grep --quiet "$grub_memtest_variable" /etc/default/grub; then
	log_start 'disabling generation of memtest options'
	if ! echo "$grub_memtest_variable" | request_sudo tee --append /etc/default/grub >/dev/null; then
		fatal 'failed to disable generation of memtest options'
	fi
	log_end
fi

log_start 're-generating Grub configuration'
request_sudo grub-mkconfig -o /boot/grub/grub.cfg
log_end

log_end
