#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component 'linux software' "$@"
}

cleanup_paths=()
cleanup() {
	if [[ ${#cleanup_paths[@]} == 0 ]]; then
		return
	fi
	rm -rf "${cleanup_paths[@]}" 2>/dev/null
}

trap cleanup EXIT

log_start 'installing Linux distribution-agnostic software'
if is_ubuntu; then
	# Get password upfront to ensure the script runs to completion without pausing
	request_sudo
fi

log_start 'removing broken binary symlinks'
find "$HOME"/.local/bin -maxdepth 1 -xtype l -delete
log_end

log_start 'removing no-longer-needed software'
rm -vrf "$HOME"/.local/bin/undercutf1
log_end

log_start 'installing b2'
install_binary_from_github_release 'b2' 'Backblaze/B2_Command_Line_Tool' 'linux'
log_end

log_start 'installing difftastic'
difftastic_url="$(get_release_url 'Wilfred/difftastic' 'difft-x86_64-unknown-linux-gnu.tar.gz')"
difftastic_tmp="$(download_to_tmp "$difftastic_url" '.tar.gz')"
difftastic_extracted_tmp="$(extract_tarball_to_tmp "$difftastic_tmp")"
cleanup_paths+=("$difftastic_extracted_tmp")
install "$difftastic_extracted_tmp"/difft "$HOME"/.local/bin/difft
log_end

log_start 'installing fnm'
fnm_url="$(get_release_url 'Schniz/fnm' 'fnm-linux.zip')"
fnm_tmp="$(download_to_tmp "$fnm_url" '.zip')"
fnm_extracted_tmp="$(extract_zip_to_tmp "$fnm_tmp")"
cleanup_paths+=("$fnm_extracted_tmp")
install "$fnm_extracted_tmp"/fnm "$HOME"/.local/bin/fnm
fnm completions --shell=zsh >"${XDG_DATA_HOME:-$HOME/.local/share}"/zsh-site-functions/_fnm
log_end

log_start 'installing git-spice'
git_spice_url="$(get_release_url 'abhinav/git-spice' '.Linux-x86_64.tar.gz')"
git_spice_tmp="$(download_to_tmp "$git_spice_url" '.tar.gz')"
git_spice_extracted_tmp="$(extract_tarball_to_tmp "$git_spice_tmp")"
cleanup_paths+=("$git_spice_extracted_tmp")
install "$git_spice_extracted_tmp"/gs "$HOME"/.local/bin/gs
git_spice_config_path="$(xdg_config)/git-spice"
mkdir -p "$git_spice_config_path"
echo '{
  "services": {
    "https://github.com": {
      "secrets": {
        "token": {
          "value": "{\"AuthenticationToken\":null,\"github_cli\":true}"
        }
      }
    }
  }
}' >"$git_spice_config_path/secrets.json"
log_end

log_start 'installing git-who'
git_who_url="$(get_release_url 'sinclairtarget/git-who' '_linux_amd64.tar.gz')"
git_who_tmp="$(download_to_tmp "$git_who_url" '.tar.gz')"
git_who_extracted_tmp="$(extract_tarball_to_tmp "$git_who_tmp")"
cleanup_paths+=("$git_who_extracted_tmp")
install "$git_who_extracted_tmp"/linux_amd64/git-who "$HOME"/.local/bin/git-who
log_end

log_start 'installing Golang'
request_sudo rm -rf /usr/local/go
go_version="$(_curl https://go.dev/VERSION?m=text | head -n 1)"
golang_tmp="$(download_to_tmp "https://go.dev/dl/$go_version.linux-amd64.tar.gz" '.tar.gz')"
cleanup_paths+=("$golang_tmp")
request_sudo tar --directory /usr/local --extract --gzip --file "$golang_tmp"
# Avoid the need for `PATH` modification by symlinking binaries to /usr/bin (same way as the distribution packages do)
request_sudo ln -sfr /usr/local/go/bin/* /usr/bin/
log_end

log_start 'installing kitty'
kitty_url="$(get_release_url 'kovidgoyal/kitty' 'x86_64.txz')"
kitty_tmp="$(download_to_tmp "$kitty_url" '.txz')"
kitty_extracted_tmp="$(extract_tarball_to_tmp "$kitty_tmp")"
cleanup_paths+=("$kitty_extracted_tmp")
kitty_path="$HOME"/.local/share/kitty
rm -rf "$kitty_path"
mv "$kitty_extracted_tmp" "$kitty_path"
_ln "$kitty_path"/bin/* "$HOME"/.local/bin
mkdir -p "$HOME"/.local/share/man/{man1,man5}
_ln "$kitty_path"/lib/kitty/shell-integration/zsh/completions/* "$(xdg_data)"/zsh-site-functions/_kitty
_ln "$kitty_path"/share/man/man1/* "$HOME"/.local/share/man/man1
_ln "$kitty_path"/share/man/man5/* "$HOME"/.local/share/man/man5
mkdir -p "$HOME"/.local/share/applications
cp "$kitty_path"/share/applications/kitty.desktop "$HOME"/.local/share/applications
sed -i "s|Icon=kitty|Icon=$HOME/.local/share/kitty/share/icons/hicolor/256x256/apps/kitty.png|g" "$HOME"/.local/share/applications/kitty*.desktop
sed -i "s|Exec=kitty|Exec=$HOME/.local/share/kitty/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
echo 'kitty.desktop' >"$HOME"/.config/xdg-terminals.list
log_end

fonts_dir="$(xdg_data)"/fonts
if ! [ -d "$fonts_dir"/input ]; then
	mkdir -p "$fonts_dir"
	log_start 'installing Input fonts'
	input_url='https://input.djr.com/build/?basic=1&fontSelection=whole&a=0&g=0&i=0&l=0&zero=0&asterisk=0&lineHeight=1.2&accept=I+do'
	input_tmp="$(download_to_tmp "$input_url" '.zip')"
	input_extracted_tmp="$(extract_zip_to_tmp "$input_tmp")"
	cleanup_paths+=("$input_extracted_tmp")
	mkdir -p "$fonts_dir"/input
	mv "$input_extracted_tmp"/Input_Fonts/*/ "$fonts_dir"/input
	if ! fc-cache "$fonts_dir"/input; then
		warn 'failed to generate font caches, font will not be available until next login'
	fi
	log_end
fi

log_start 'installing shfmt'
install_binary_from_github_release 'shfmt' 'mvdan/sh' 'linux_amd64'
log_end

log_start 'installing Bitwarden CLI'
bw_tmp="$(download_to_tmp 'https://vault.bitwarden.com/download/?app=cli&platform=linux' '.zip')"
bw_extracted_tmp="$(extract_zip_to_tmp "$bw_tmp")"
cleanup_paths+=("$bw_extracted_tmp")
install "$bw_extracted_tmp"/bw "$HOME"/.local/bin/bw
log_end

log_start 'installing NextCloud'
install_binary_from_github_release 'nextcloud' 'nextcloud-releases/desktop' 'x86_64.AppImage'
log_end

log_start 'installing restic'
restic_url="$(get_release_url 'restic/restic' '_linux_amd64.bz2')"
restic_archive="$(download_to_tmp "$restic_url" '.bz2')"
cleanup_paths+=("$restic_archive")
restic_binary_tmp="$(mktemp)"
cleanup_paths+=("$restic_binary_tmp")
bzip2 -dc "$restic_archive" >"$restic_binary_tmp"
install "$restic_binary_tmp" "$HOME"/.local/bin/restic
log_end

log_start 'installing uv'
uv_url="$(get_release_url 'astral-sh/uv' 'uv-x86_64-unknown-linux-gnu.tar.gz')"
uv_tmp="$(download_to_tmp "$uv_url" '.tar.gz')"
uv_extracted_tmp="$(extract_tarball_to_tmp "$uv_tmp" --strip-components 1)"
cleanup_paths+=("$uv_extracted_tmp")
install "$uv_extracted_tmp"/{uv,uvx} "$HOME"/.local/bin
log_end

log_start 'installing websocat'
install_binary_from_github_release 'websocat' 'vi/websocat' 'x86_64-unknown-linux-musl'
log_end

log_start 'installing yt-dlp'
install_binary_from_github_release 'yt-dlp' 'yt-dlp/yt-dlp' '_linux'
log_end

log_start 'installing YubiKey Manager'
install_binary_from_url 'yubikey-manager' 'https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-latest-linux.AppImage'
log_end

if is_ubuntu; then
	log_start 'installing bat'
	if ! request_sudo apt-mark unhold bat; then
		warn 'failed to unhold bat, skipping installation'
	else
		install_deb_from_github_release 'sharkdp/bat' '_amd64.deb'
	fi
	# Tell apt to not upgrade bat using the repository version
	if ! request_sudo apt-mark hold bat; then
		warn 'failed to hold bat, apt upgrade may override its installation'
	fi
	log_end

	log_start 'installing Bitwarden'
	install_deb_from_url 'https://bitwarden.com/download/?app=desktop&platform=linux&variant=deb'
	log_end

	log_start 'installing darkman'
	if command -v scdoc >/dev/null; then
		darkman_tmp="$(mktemp -d)"
		cleanup_paths+=("$darkman_tmp")
		git clone https://gitlab.com/WhyNotHugo/darkman.git "$darkman_tmp"
		(
			cd "$darkman_tmp"
			make
			request_sudo make install
		)
	else
		warn 'skipping darkman installation because scdoc is not installed'
	fi
	log_end

	log_start 'installing DBeaver'
	install_deb_from_github_release 'dbeaver/dbeaver' '_amd64.deb'
	log_end

	log_start 'installing git-delta'
	install_deb_from_github_release 'dandavison/delta' '_amd64.deb'
	log_end

	log_start 'installing glow'
	install_deb_from_github_release 'charmbracelet/glow' '_amd64.deb'
	log_end

	log_start 'installing go-hass-agent'
	install_deb_from_github_release 'joshuar/go-hass-agent' '_amd64.deb'
	mkdir -p "$HOME"/.config/go-hass-agent/scripts
	_ln "$_dir"/../config/go-hass-agent/audio-output "$HOME"/.config/go-hass-agent/scripts
	_ln "$_dir"/../config/go-hass-agent/webcam-in-use "$HOME"/.config/go-hass-agent/scripts
	log_end

	log_start 'installing Hugo'
	install_deb_from_github_release 'gohugoio/hugo' 'linux-amd64.deb'
	log_end

	log_start 'installing hyperfine'
	install_deb_from_github_release 'sharkdp/hyperfine' '_amd64.deb'
	log_end

	log_start 'installing Obsidian'
	install_deb_from_github_release 'obsidianmd/obsidian-releases' '_amd64.deb'
	log_end

	log_start 'removing no-longer-needed software'
	request_sudo apt-get remove --yes --autoremove jan &>/dev/null || true
	log_end
fi

log_end
