#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component macos "$@"
}

log_start 'setting up macOS'

log_start 'symlinking Hammerspoon config'
mkdir -p "$HOME"/.hammerspoon
_ln "$_dir"/../config/hammerspoon.lua "$HOME"/.hammerspoon/init.lua
log_end

# Enable tap to click
defaults write com.apple.driver.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Enable full keyboard access for all controls (e.g. tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

# Use function keys as standard function keys
defaults write NSGlobalDomain com.apple.keyboard.fnState -int 1

# Disable natural scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# Don't animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Remove all default dock icons
if defaults read com.apple.dock persistent-apps | grep --quiet 'com.apple.Photos'; then
	defaults write com.apple.dock persistent-apps -array
fi

# Disable user interface sound effects
defaults write NSGlobalDomain com.apple.sound.uiaudio.enabled -int 0

# Disable the sound effects on boot
request_sudo nvram SystemAudioVolume=" "

# Set hostname if the current hostname has capital letters (heuristic for detecting default value)
if echo "$HOSTNAME" | grep --quiet -E '[A-Z]+'; then
	log_start 'configuring hostname'
	read -r -p "$(make_prompt 'Hostname') " hostname
	request_sudo scutil --set ComputerName "$hostname"
	request_sudo scutil --set HostName "$hostname"
	request_sudo scutil --set LocalHostName "$hostname"
	request_sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$hostname"
	log_end
fi

# Disable screensaver
request_sudo osascript -e 'tell application "System Events" to set delay interval of screen saver preferences to 0'

# Set machine sleep while charging (minutes)
request_sudo pmset -c displaysleep 180
request_sudo pmset -c sleep 180

# Set machine sleep on battery (minutes)
request_sudo pmset -b displaysleep 20
request_sudo pmset -b sleep 20

# Install Rosetta 2
if ! pgrep oahd &>/dev/null; then
	softwareupdate --install-rosetta --agree-to-license
fi

# Restart Dock and Finder
killall Dock
killall Finder

log_end
