#!/usr/bin/env bash

set -euo pipefail

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component main "$@"
}

# Ask for password at start
# shellcheck disable=SC2119
request_sudo

"$_dir"/config

log_start 'running OS-specific scripts'

if is_macos; then
	"$_dir"/macos
	"$_dir"/brew
elif is_linux; then
	"$_dir"/linux-software
	"$_dir"/flatpak
	if command -v apt >/dev/null; then
		"$_dir"/apt
	fi
	"$_dir"/grub
	if is_ubuntu; then
		"$_dir"/ubuntu
		"$_dir"/gnome-theme
	fi
	if is_ubuntu || is_debian; then
		"$_dir"/remote-management
	fi
fi

log_end

log_start 'running programming language setup scripts'
"$_dir"/golang
"$_dir"/node
"$_dir"/pip
log_end

log_start 'running application setup scripts'
"$_dir"/emacs
"$_dir"/git
"$_dir"/gh
"$_dir"/gpg
"$_dir"/ssh
"$_dir"/vscode
"$_dir"/zsh
log_end

log_start 'running system setup scripts'
"$_dir"/profile-picture
"$_dir"/ssh-key
"$_dir"/gpg-keys
log_end

log "done. start a new login shell or run 'source zsh/.zshrc'."
