#!/usr/bin/env bash

# This script must run after the OS-specific scripts because it depends on fnm.

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component node "$@"
}

log_start 'setting up Node'

log_start 'installing latest Node version'
if ! fnm install --latest; then
	warn 'failed to install latest Node version'
fi
log_end

log_start 'setting default Node version'
if latest_node_version="$(fnm list-remote --latest)"; then
	if ! fnm default "$latest_node_version"; then
		warn 'failed to set default Node version'
	fi
else
	warn 'failed to get latest Node version'
fi
log_end

if is_macos && [ -f "$NPM_CONFIG_USERCONFIG" ] && ! [ -h "$HOME"/.npmrc ]; then
	log_start 'linking npmrc to home directory'
	ln -sf "$NPM_CONFIG_USERCONFIG" "$HOME"/.npmrc
	log_end
fi

log_start 'removing nodenv'
rm -rf ~/.local/share/nodenv/ || true
log_end

log_end
