#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component pip "$@"
}

log_start 'installing pip tools'
pip_packages=(
	# Update pip first to suppress warnings about it being outdated
	pip # Package manager

	b2                   # Backblaze B2 CLI
	csvkit               # CSV processing tools
	homeassistant-cli    # Home Assistant management tool
	khal                 # Calendar CLI
	visidata             # Data set visualizer
	vdirsyncer           # Synchronize calendars and contacts
	'vdirsyncer[google]' # Extension for Google support
	youtube-dl           # Media downloader
)

for package in "${pip_packages[@]}"; do
	# Disable keyring to prevent interactive prompts (https://github.com/pypa/pip/issues/8090#issuecomment-803363268)
	PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring python3 -m pip install --upgrade --user "$package" >/dev/null
	log "installed \"$package\""
done

if is_linux; then
	log_start 'installing rofimoji'
	if ! rofimoji_url="$(get_release_url 'fdw/rofimoji' '.whl')"; then
		fatal 'failed to get rofimoji release URL'
	fi
	rofimoji_wheel="$(basename "$rofimoji_url")"
	if ! _curl "$rofimoji_url" --output "$rofimoji_wheel"; then
		fatal 'failed to download rofimoji'
	fi
	if ! pip install --user "$rofimoji_wheel"; then
		fatal 'failed to install rofimoji'
	fi
	rm -f "$rofimoji_wheel"

	_ln "$_dir"/../config/rofimoji.rc "$(xdg_config)"/rofimoji.rc
	log_end
fi

log_end
