#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

message "installing pip tools..."
pip_packages=(
	csvkit   # CSV processing tools
	pip      # Package manager
	visidata # Data set visualizer
)

for package in "${pip_packages[@]}"; do
	python3 -m pip install --upgrade --user "$package" >/dev/null
	message "  %s" "installed $package"
done
message "pip done."
