#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log() {
	log_with_component tmux "$@"
}

log_start 'setting up Tmux'

log_start 'initializing Tmux configuration'
config_path="$(xdg_config)"/tmux
mkdir -p "$config_path"

if [ -h "$HOME"/.tmux.conf ]; then
	log 'removing old configuration file'
	rm -f "$HOME"/.tmux.conf
fi
ln -sf "$_dir"/../config/tmux.conf "$config_path"
log_end

log_start 'initializing Tmux Plugin Manager'
readonly tpm_path="$(xdg_data)"/tmux/plugins/tpm
if ! [ -d "$tpm_path" ]; then
	git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm_path"
else
	log 'Tmux Plugin Manager already initialized'
fi
log_end

log_end
