#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

log 'initializing Tmux configuration...'
config_path="$(xdg_config)"/tmux
mkdir -p "$config_path"

if [ -h "$HOME"/.tmux.conf ]; then
	message "  %s" "removing old configuration file..."
	rm -f "$HOME"/.tmux.conf
fi
ln -sf "$_dir"/../config/tmux.conf "$config_path"
log 'done initializing Tmux configuration.'

log 'initializing Tmux Plugin Manager...'
readonly tpm_path="$(xdg_data)"/tmux/plugins/tpm
if ! [ -d "$tpm_path" ]; then
	git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm_path"
	log 'done initializing Tmux Plugin Manager.'
else
	log 'Tmux Plugin Manager already initialized.'
fi
