# Create a pull request
# $1: base branch
# $2: title
prc: >-
  !gh pr create
  --assignee=@me
  --base="$1"
  --body="$(gh pr-body-commits "$1")"
  --title="$2"
  "${@:3}"
  && gh pr view --web

# Create a draft pull request
# $1: base branch
# $2: title
prcd: >-
  !gh prc "$1" "$2" --draft

# Get the base branch for the current branch's pull request
# shellcheck disable=SC2016
prbase: >-
  pr view --json baseRefName --jq '.baseRefName'

# Convenience shortcut for checking out a pull request
co: >-
  pr checkout

# Set a pull request to auto-merge
# $1: commit to get merge commit body from, defaults to "HEAD"
automerge: >-
  !gh pr merge
  --squash
  --subject="$(gh pr view --json=title,number --template="{{ .title }} (#{{ .number }})")"
  --body="$(git show --no-patch --pretty="%b" "${1:-HEAD}")"
  --auto
  && gh pr view
  --json=autoMergeRequest
  --template="Merge commit message:{{ \"\n\" }}{{ .autoMergeRequest.commitHeadline }}{{ \"\n\" }}{{ .autoMergeRequest.commitBody }}"