# Create a pull request
# $1: base branch
# $2: title
# $3+: other parameters for `gh pr create`
prc: >-
  !gh pr create
  --assignee=@me
  --base="$1"
  --body="$(gh pr-body-commits "$1")"
  --title="$2"
  "${@:3}"
  && gh pr view --web

# Create a draft pull request
# $1: base branch
# $2: title
# $3+: other parameters for `gh pr create`
prcd: >-
  !gh prc "$1" "$2" "${@:3}" --draft

# Get the base branch for the current branch's pull request
# shellcheck disable=SC2016
prbase: >-
  pr view --json baseRefName --jq '.baseRefName'

# Convenience shortcut for checking out a pull request
co: >-
  pr checkout

# Inverse of "co": switch back to the previous branch and delete the current branch
unco: >-
  !git switch - && git branch --delete @{-1} 

# Merge a pull request (squash)
# $1: commit to get merge commit body from, defaults to "HEAD"
# $2+: other parameters for `gh pr merge`
merge: >-
  !subject="$(gh pr view --json=title,number --template="{{ .title }} (#{{ .number }})")" &&
  body="$(git show --no-patch --pretty="%b" "${1:-HEAD}")" &&
  read -r -p "${subject}


  ${body}


  → Press enter to proceed with this commit message " &&
  gh pr merge
  --squash
  --subject="$subject"
  --body="$body"
  --delete-branch
  "${@:2}"

# Set a pull request to auto-merge (squash)
# $1: commit to get merge commit body from, defaults to "HEAD"
# $2+: other parameters for `gh pr merge`
automerge: >-
  !gh merge
  "$1"
  --auto
  "${@:2}"
  && gh pr view
  --json=autoMergeRequest
  --template="Merge commit message:{{ \"\n\" }}{{ .autoMergeRequest.commitHeadline }}{{ \"\n\" }}{{ .autoMergeRequest.commitBody }}"

# Search for pull requests
# - `gh` will not implement hyperlinks; here the pull request numbers are hyperlinks
# - The default output of  gh pr list  does not include the author's name; here the author name is included instead of
#   the base branch
# $1: search, see `gh pr list`'s `--search` flag
pr-search: >-
  !gh pr list
  --search="$1"
  --json author,number,title,updatedAt,url
  --template='
  {{- range . -}}
    {{tablerow (hyperlink .url (printf "#%v" .number | autocolor "green")) .title .author.name (timeago .updatedAt) }}
  {{- else -}}
    {{ "No pull requests" }}
    {{- "\n"}}
  {{- end -}}
  {{tablerender}}'

# List pull requests in a repository that you may want to review
# - Created in the past four days.
# - Not reviewed by you.
# - Not authored by you.
# - Not a draft
prs-to-review: >-
  !gh pr-search "is:open -reviewed-by:@me -author:@me draft:false created:>=$(gdate --iso-8601 --date='4 days ago')"
