monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-CalDigit__Inc._CalDigit_Thunderbolt_3_Audio-00" }
      { device.name = "alsa_card.usb-046d_Logitech_BRIO_22514137-03" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
