#!/usr/bin/env bash

set -euo pipefail

# Back up computer-local files known to this repository.

if ! command -v gh >/dev/null; then
	echo 'gh must be installed'
	exit 1
fi

if ! gh auth status &>/dev/null; then
	echo 'gh must be authenticated'
	exit 1
fi

echo "using hostname \"${HOSTNAME}\""
echo

gist_name="dotfiles-locals-backup-${HOSTNAME}"

if ! all_gists="$(gh api 'gists')"; then
	echo 'error: failed to get all gists'
	exit 1
fi

if ! gist_to_update="$(echo "$all_gists" | jq \
	--arg gist_name "$gist_name" \
	--join-output \
	'map(select(.description == $gist_name)) | .[] | .id')"; then
	echo 'error: failed to extract gist to update from all gists'
	exit 1
fi

emacs_local_config_dir="${XDG_CONFIG_HOME:-"$HOME"/.config}"/emacs
candidate_files=(
	"$HOME"/.locals
	"$HOME"/.profile-local
	"$emacs_local_config_dir"/lisp/*
	"${XDG_DATA_HOME:-$HOME/.local/share}"/dotfiles/,update-local
	"${XDG_CONFIG_HOME:-$HOME/.config}"/i3/login-local
	"${XDG_CONFIG_HOME:-$HOME/.config}"/i3/workspaces/*
)

files=()

for f in "${candidate_files[@]}"; do
	if [ -f "$f" ]; then
		files+=("$(realpath --relative-to="$HOME" "$f")")
	fi
done

echo "found files:"
printf -- ' - %s\n' "${files[@]}"
echo

# Ensure all file paths are relative to home directory
cd "$HOME"

if [ -z "$gist_to_update" ]; then
	echo 'no existing gist, creating...'
	gh gist create --desc "$gist_name" "${files[@]}"
	exit
fi

echo 'found existing gist, updating...'
echo

for f in "${files[@]}"; do
	echo "→ $f"
	f_basename="$(basename "$f")"
	if [ -s "$f" ] && ! existing_content="$(gh gist view "$gist_to_update" --filename="$f_basename")"; then
		echo "  adding new file..."
		gh gist edit "$gist_to_update" --add="$f"
	else
		if ! diff -w <(echo "$existing_content") "$f" >/dev/null; then
			echo "  updating existing file..."
			gh gist edit "$gist_to_update" --filename="$f_basename" "$f"
		else
			echo "  file is unchanged, skipping"
		fi
	fi
done
